cat output\paulwhite_2023_01.xml | sed "1,1d; $d" > output\latest_episodes.xml

cat output\paulwhite_2022_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2022_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2021_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2021_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2020_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2020_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2019_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2019_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2018_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2018_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2017_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2017_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2016_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2016_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2015_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2015_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2014_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2014_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2013_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2013_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2012_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2012_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2011_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2011_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2010_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_04.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_03.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_02.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2010_01.xml | sed "1,1d; $d" >> output\latest_episodes.xml

cat output\paulwhite_2009_12.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_11.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_10.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_09.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_08.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_07.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_06.xml | sed "1,1d; $d" >> output\latest_episodes.xml
cat output\paulwhite_2009_05.xml | sed "1,1d; $d" >> output\latest_episodes.xml